openapi: 3.0.1
info:
  title: CustomerManagementOrchestrator
  description: API Definition of CustomerManagementOrchestrator
  version: 1.0.0
servers:
- url: http://localhost:8290/customer-mgt
paths:
  /customer:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
